import Foundation

/// A space-reclaim suggestion surfaced from the scanned tree.
struct CleanupSuggestion: Identifiable {
    let id = UUID()
    let category: Category
    let url: URL
    let size: Int64
    let detail: String

    enum Category: String, CaseIterable, Identifiable {
        case buildArtifacts = "Build artifacts"
        case caches = "Caches"
        case junk = "Junk files"
        case largeArchives = "Large archives & installers"
        case emptyFolders = "Empty folders"
        case brokenLinks = "Broken aliases"

        var id: String { rawValue }
        var icon: String {
            switch self {
            case .buildArtifacts: return "hammer.fill"
            case .caches: return "arrow.triangle.2.circlepath"
            case .junk: return "trash.fill"
            case .largeArchives: return "shippingbox.fill"
            case .emptyFolders: return "folder.badge.minus"
            case .brokenLinks: return "link"
            }
        }
        var blurb: String {
            switch self {
            case .buildArtifacts: return "Regenerated by your build tools. Safe to remove."
            case .caches: return "Apps rebuild these automatically."
            case .junk: return "Leftover temp files and incomplete downloads."
            case .largeArchives: return "Big downloads you may no longer need."
            case .emptyFolders: return "Folders with nothing inside."
            case .brokenLinks: return "Aliases whose target no longer exists."
            }
        }
    }
}

enum CleanupRules {
    // Directory names whose entire contents are reclaimable build output.
    private static let buildDirs: Set<String> = [
        // JS/web
        "node_modules", ".next", ".nuxt", ".svelte-kit", ".expo", "dist", "build",
        ".turbo", ".parcel-cache", ".angular", ".nyc_output",
        // native / Apple
        "DerivedData", "iOS DeviceSupport", "Pods", "Carthage", ".swiftpm",
        // Rust / JVM / Go / Haskell / Elm
        "target", ".gradle", ".stack-work", "elm-stuff",
        // Python
        "__pycache__", ".pytest_cache", ".mypy_cache", ".dart_tool", ".venv", "venv", ".tox",
        // misc regenerable
        ".terraform", ".cache"
    ]
    private static let cacheDirs: Set<String> = ["Caches", "Cache", ".npm", ".cache"]
    private static let junkExtensions: Set<String> = ["crdownload", "part", "download", "tmp"]
    private static let junkNames: Set<String> = [".DS_Store", "Thumbs.db"]
    private static let archiveExtensions: Set<String> = ["dmg", "iso", "pkg", "zip", "tar", "gz", "tgz", "xz", "rar", "7z"]

    private static var archiveMinBytes: Int64 {
        let mb = UserDefaults.standard.integer(forKey: "archiveMinMB")
        return Int64(mb == 0 ? 100 : mb) * 1024 * 1024
    }

    static func analyze(_ root: FileNode) -> [CleanupSuggestion] {
        var out: [CleanupSuggestion] = []

        func walk(_ node: FileNode, insidePrunedDir: Bool) {
            if node.isDirectory {
                let lower = node.name.lowercased()
                // Whole-directory build artifacts — flag and don't descend.
                if buildDirs.contains(node.name) || buildDirs.contains(lower) {
                    if node.size > 0 {
                        out.append(.init(category: .buildArtifacts, url: node.url, size: node.size,
                                         detail: "\(node.fileCount) files"))
                    }
                    return
                }
                if cacheDirs.contains(node.name) {
                    if node.size > 0 {
                        out.append(.init(category: .caches, url: node.url, size: node.size,
                                         detail: "\(node.fileCount) files"))
                    }
                    return
                }
                if node.url != root.url, node.children.isEmpty, node.fileCount == 0 {
                    out.append(.init(category: .emptyFolders, url: node.url, size: node.size, detail: "empty"))
                    return
                }
                for c in node.children { walk(c, insidePrunedDir: insidePrunedDir) }
            } else if node.isSymlink {
                if isBrokenSymlink(node.url) {
                    out.append(.init(category: .brokenLinks, url: node.url, size: 0, detail: "broken"))
                }
            } else {
                if junkNames.contains(node.name) || junkExtensions.contains(node.fileExtension) {
                    out.append(.init(category: .junk, url: node.url, size: node.size,
                                     detail: node.fileExtension.isEmpty ? "temp file" : ".\(node.fileExtension)"))
                } else if archiveExtensions.contains(node.fileExtension), node.size >= archiveMinBytes {
                    out.append(.init(category: .largeArchives, url: node.url, size: node.size,
                                     detail: ".\(node.fileExtension)"))
                }
            }
        }

        func isBrokenSymlink(_ url: URL) -> Bool { CleanupRules.isBrokenSymlink(url) }

        walk(root, insidePrunedDir: false)
        return out.sorted { $0.size > $1.size }
    }

    /// Whether `url` is a symlink/alias whose target no longer exists.
    static func isBrokenSymlink(_ url: URL) -> Bool {
        let fm = FileManager.default
        guard let dest = try? fm.destinationOfSymbolicLink(atPath: url.path) else { return false }
        let resolved = (dest as NSString).isAbsolutePath
            ? dest
            : (url.deletingLastPathComponent().path as NSString).appendingPathComponent(dest)
        return !fm.fileExists(atPath: resolved)
    }
}
