import Foundation

/// A space-reclaim suggestion surfaced from the scanned tree.
struct CleanupSuggestion: Identifiable {
    let id = UUID()
    let category: Category
    let url: URL
    let size: Int64
    let detail: String

    enum Category: String, CaseIterable, Identifiable {
        case buildArtifacts = "Build artifacts"
        case caches = "Caches"
        case junk = "Junk files"
        case largeArchives = "Large archives & installers"

        var id: String { rawValue }
        var icon: String {
            switch self {
            case .buildArtifacts: return "hammer.fill"
            case .caches: return "arrow.triangle.2.circlepath"
            case .junk: return "trash.fill"
            case .largeArchives: return "shippingbox.fill"
            }
        }
        var blurb: String {
            switch self {
            case .buildArtifacts: return "Regenerated by your build tools. Safe to remove."
            case .caches: return "Apps rebuild these automatically."
            case .junk: return "Leftover temp files and incomplete downloads."
            case .largeArchives: return "Big downloads you may no longer need."
            }
        }
    }
}

enum CleanupRules {
    // Directory names whose entire contents are reclaimable build output.
    private static let buildDirs: Set<String> = [
        "node_modules", ".next", "dist", "build", ".turbo", ".parcel-cache",
        "target", ".gradle", "DerivedData", ".dart_tool", "Pods", "__pycache__",
        ".pytest_cache", ".mypy_cache", ".cache"
    ]
    private static let cacheDirs: Set<String> = ["Caches", "Cache", ".npm", ".cache"]
    private static let junkExtensions: Set<String> = ["crdownload", "part", "download", "tmp"]
    private static let junkNames: Set<String> = [".DS_Store", "Thumbs.db"]
    private static let archiveExtensions: Set<String> = ["dmg", "iso", "pkg", "zip", "tar", "gz", "tgz", "xz", "rar", "7z"]

    private static var archiveMinBytes: Int64 {
        let mb = UserDefaults.standard.integer(forKey: "archiveMinMB")
        return Int64(mb == 0 ? 100 : mb) * 1024 * 1024
    }

    static func analyze(_ root: FileNode) -> [CleanupSuggestion] {
        var out: [CleanupSuggestion] = []

        func walk(_ node: FileNode, insidePrunedDir: Bool) {
            if node.isDirectory {
                let lower = node.name.lowercased()
                // Whole-directory build artifacts — flag and don't descend.
                if buildDirs.contains(node.name) || buildDirs.contains(lower) {
                    if node.size > 0 {
                        out.append(.init(category: .buildArtifacts, url: node.url, size: node.size,
                                         detail: "\(node.fileCount) files"))
                    }
                    return
                }
                if cacheDirs.contains(node.name) {
                    if node.size > 0 {
                        out.append(.init(category: .caches, url: node.url, size: node.size,
                                         detail: "\(node.fileCount) files"))
                    }
                    return
                }
                for c in node.children { walk(c, insidePrunedDir: insidePrunedDir) }
            } else {
                if junkNames.contains(node.name) || junkExtensions.contains(node.fileExtension) {
                    out.append(.init(category: .junk, url: node.url, size: node.size,
                                     detail: node.fileExtension.isEmpty ? "temp file" : ".\(node.fileExtension)"))
                } else if archiveExtensions.contains(node.fileExtension), node.size >= archiveMinBytes {
                    out.append(.init(category: .largeArchives, url: node.url, size: node.size,
                                     detail: ".\(node.fileExtension)"))
                }
            }
        }

        walk(root, insidePrunedDir: false)
        return out.sorted { $0.size > $1.size }
    }
}
