import Foundation

/// Builds a shareable Markdown report of a scan (total, by-type, largest items
/// and files). Pure — no I/O — so it's easy to test and to call off the main actor.
enum ReportBuilder {
    static func markdown(root: FileNode, insights: ScanInsights, scannedRoot: URL?, date: Date) -> String {
        var s = "# DiskLens report\n\n"
        s += "- **Folder:** \(scannedRoot?.path ?? root.name)\n"
        s += "- **Scanned:** \(date.formatted(date: .abbreviated, time: .shortened))\n"
        s += "- **Total:** \(ByteFormat.string(insights.totalBytes))\n"
        s += "- **Files:** \(insights.totalFiles.formatted())\n\n"

        s += "## Usage by type\n\n| Type | Size | Files |\n| --- | --- | --- |\n"
        for c in insights.categories {
            s += "| \(c.label) | \(ByteFormat.string(c.bytes)) | \(c.count) |\n"
        }

        s += "\n## Largest items\n\n| Item | Size |\n| --- | --- |\n"
        for i in insights.topItems {
            s += "| \(i.name) | \(ByteFormat.string(i.size)) |\n"
        }

        s += "\n## Largest files\n\n| File | Size | Location |\n| --- | --- | --- |\n"
        for f in insights.topFiles.prefix(100) {
            s += "| \(f.name) | \(ByteFormat.string(f.size)) | \(f.url.deletingLastPathComponent().path) |\n"
        }

        s += "\n_Generated by DiskLens._\n"
        return s
    }
}
